encoding: UTF-8
url: https://creatingsapien.github.io  #mayraaleli85.github.io
baseurl: ""

# Site settings
title: Austin Capital Data
email: gunnar@austincapitaldata.com
description: "A place for people to discuss thier creations"

# Team names, titles and social links
people:
- name: Gunnar Kleemann
  pic: 4
  position: Principal Data Scientist
  social:
    - title: twitter
      url: #
    - title: facebook
      url: 
    - title: stack-overflow
      url: #

- name: Robert Foster 
  pic: 8
  position: Data Scientist/ Curriculum Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Joe Mirza
  pic: 9
  position: Data Science Intern
  social:
    - title: twitter
      url: #
    - title: facebook
      url: 
    - title: stack-overflow
      url: #
  
- name: Tim Chen
  pic: 12
  position: Data Science Intern
  social:
    - title: twitter
      url: 
    - title: linkedin
      url: https://www.linkedin.com/in/chentim/
    - title: stack-overflow
      url: #

- name: Skylar Chadwick
  pic: 6
  position: Content Strategist
  social:
    - title: twitter
      url: #
    - title: facebook
      url: 
    - title: stack-overflow
      url: #

- name: Mayra Castro
  pic: 7
  position: Project Manager
  social:
    - title: twitter
      url: #
    - title: facebook
      url: 
    - title: stack-overflow
      url: #

alumni:
- name: Kiersten Henderson
  pic: 11
  position: Alumni, Data Scientist
  social:
    - title: twitter
      url: #
    - title: linkedin
      url: https://www.linkedin.com/in/kierstenhenderson/
    - title: stack-overflow
      url: #

- name: Justine Chia
  pic: 10
  position: Alumni, Data Scientist
  social:
    - title: twitter
      url: #
    - title: linkedin
      url: https://www.linkedin.com/in/justinechia/
    - title: stack-overflow
      url: #


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 9701 Dessau Rd #304
  - line: Austin, TX 78754

# Build settings
markdown: kramdown
permalink: pretty
